<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SP0001_ParaBank_TC001_23_Loging_Function</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0737b98e-2e2b-4ba2-be1e-53befc22d4b6</testSuiteGuid>
   <testCaseLink>
      <guid>48a9a08a-a8a7-4dd6-8c02-efb61ebd2e60</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loging_Functions/SP0001_ParaBank_TC001_23_Loging_Valid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a273634-a367-49fb-90f8-9f083c61fa18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbd58a74-5705-4e39-a43e-255b3a5282d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab8895b2-dac1-4ab8-981c-cfbcdb844822</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Loging_Functions/SP0001_ParaBank_TC002_23_Loging_InValid</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe867b06-7fd4-481f-9c38-823813567b08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bd6a1ff-bb5b-42c6-a433-956d449ab90d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
